using Npgsql;
using ReservationService.Application;
using ReservationService.Domain;
namespace ReservationService.Infrastructure;
public sealed class PostgresReservationRepository(string cs) : IReservationRepository
{
    private NpgsqlConnection Db() => new(cs);
    private static Hotel H(NpgsqlDataReader r, int o = 0) => new(r.GetInt32(o), r.GetGuid(o + 1), r.GetString(o + 2), r.GetString(o + 3), r.GetString(o + 4), r.GetString(o + 5), r.GetInt32(o + 6), r.GetInt32(o + 7));
    private static Reservation R(NpgsqlDataReader r) => new(r.GetGuid(0), r.GetString(1), r.GetGuid(2), r.GetInt32(3), Enum.Parse<ReservationStatus>(r.GetString(4)), DateOnly.FromDateTime(r.GetDateTime(5)), DateOnly.FromDateTime(r.GetDateTime(6)));
    public async Task<(IReadOnlyList<Hotel>, long)> GetHotelsAsync(int page, int size, CancellationToken ct) { await using var db = Db(); await db.OpenAsync(ct); await using var c = new NpgsqlCommand("SELECT COUNT(*) FROM hotels", db); var total = (long)(await c.ExecuteScalarAsync(ct))!; await using var cmd = new NpgsqlCommand("SELECT id,hotel_uid,name,country,city,address,stars,price FROM hotels ORDER BY id LIMIT @s OFFSET @o", db); cmd.Parameters.AddWithValue("s", size); cmd.Parameters.AddWithValue("o", (page - 1) * size); await using var r = await cmd.ExecuteReaderAsync(ct); var a = new List<Hotel>(); while (await r.ReadAsync(ct)) a.Add(H(r)); return (a, total); }
    public async Task<Hotel?> GetHotelAsync(Guid uid, CancellationToken ct) { await using var db = Db(); await db.OpenAsync(ct); await using var cmd = new NpgsqlCommand("SELECT id,hotel_uid,name,country,city,address,stars,price FROM hotels WHERE hotel_uid=@u", db); cmd.Parameters.AddWithValue("u", uid); await using var r = await cmd.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? H(r) : null; }
    private const string JoinSql = "SELECT r.reservation_uid,r.username,r.payment_uid,r.hotel_id,r.status,r.start_date,r.end_date,h.id,h.hotel_uid,h.name,h.country,h.city,h.address,h.stars,h.price FROM reservation r JOIN hotels h ON h.id=r.hotel_id ";
    public async Task<IReadOnlyList<(Reservation, Hotel)>> GetReservationsAsync(string username, CancellationToken ct) { await using var db = Db(); await db.OpenAsync(ct); await using var cmd = new NpgsqlCommand(JoinSql + "WHERE r.username=@x ORDER BY r.id", db); cmd.Parameters.AddWithValue("x", username); await using var r = await cmd.ExecuteReaderAsync(ct); var a = new List<(Reservation, Hotel)>(); while (await r.ReadAsync(ct)) a.Add((R(r), H(r, 7))); return a; }
    public async Task<(Reservation, Hotel)?> GetReservationAsync(Guid uid, CancellationToken ct) { await using var db = Db(); await db.OpenAsync(ct); await using var cmd = new NpgsqlCommand(JoinSql + "WHERE r.reservation_uid=@u", db); cmd.Parameters.AddWithValue("u", uid); await using var r = await cmd.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? (R(r), H(r, 7)) : null; }
    public async Task CreateAsync(Reservation x, CancellationToken ct) { await using var db = Db(); await db.OpenAsync(ct); await using var cmd = new NpgsqlCommand("INSERT INTO reservation(reservation_uid,username,payment_uid,hotel_id,status,start_date,end_date) VALUES(@u,@n,@p,@h,@s,@a,@b)", db); cmd.Parameters.AddWithValue("u", x.ReservationUid); cmd.Parameters.AddWithValue("n", x.Username); cmd.Parameters.AddWithValue("p", x.PaymentUid); cmd.Parameters.AddWithValue("h", x.HotelId); cmd.Parameters.AddWithValue("s", x.Status.ToString()); cmd.Parameters.AddWithValue("a", x.StartDate); cmd.Parameters.AddWithValue("b", x.EndDate); await cmd.ExecuteNonQueryAsync(ct); }
    public async Task<bool> CancelAsync(Guid uid, string username, CancellationToken ct) { await using var db = Db(); await db.OpenAsync(ct); await using var cmd = new NpgsqlCommand("UPDATE reservation SET status='CANCELED' WHERE reservation_uid=@u AND username=@n", db); cmd.Parameters.AddWithValue("u", uid); cmd.Parameters.AddWithValue("n", username); return await cmd.ExecuteNonQueryAsync(ct) > 0; }
}
